### ISSUE TITLE
SVG <clipPath> tag is erroneously lowercased

### ISSUE THREAD

**Issue by RussianCow** [remarkablemark/html-dom-parser#13]
Any SVG `<clipPath>` elements in the parsed document have their tag names lowercased. Unfortunately, SVG is case-sensitive, so this is incorrect.

Smallest reproducible example:
```javascript
const htmlDomParser = require('html-dom-parser')
const dom = htmlDomParser('<svg><clipPath></clipPath></svg>')
dom[0].children[0].name == 'clippath' // true
```

I can try to submit a PR, but I haven't gotten far enough to pin-point the source of the issue yet.

**Comment by RussianCow** [comment]
Actually, I just found [the offending line](https://github.com/remarkablemark/html-dom-parser/blob/7f55061ed8458d77b65dd9922fe53d8902f4e6ad/lib/utilities.js#L57) in `lib/utilities.js`:
```javascript
nodeObj.name = node.nodeName.toLowerCase();
```
I'll have a PR ready shortly.

**Comment by remarkablemark** [comment]
To summarize my comment from #14, it seems that [htmlparser2](https://github.com/fb55/htmlparser2/issues/79) is not spec-compliant so I'm considering replacing it with [parse5](https://github.com/inikulin/parse5) for server-side parsing.

**Comment by remarkablemark** [comment]
`html-dom-parser@0.2.2` has been published:

```sh
# update with npm
npm i -S html-dom-parser@0.2.2

# or with yarn
yarn add html-dom-parser@0.2.2
```

Thanks for your help in getting this out @RussianCow!

**Comment by RussianCow** [comment]
Great! You're very welcome, and thank you so much for getting this out so quick!
