### ISSUE TITLE
Support `template` tags

### ISSUE THREAD

**Issue by loganvolkers** [remarkablemark/html-dom-parser#216]
The current implementation won't parse `<template>` tags correctly.

This is because `<template>` tags use `node.content.childNodes` instead of `node.childNodes` for tracking their children.

Related line: https://github.com/remarkablemark/html-dom-parser/blob/master/lib/client/utilities.js#L86

**Comment by remarkablemark** [comment]
Thanks for opening this issue @loganvolkers. Would you like to open a PR?

**Comment by loganvolkers** [comment]
I'm working on a rewrite in Typescript for the browser at the moment. Once that project's done might have time to port the logic back.

**Comment by remarkablemark** [comment]
Sounds good @loganvolkers!

**Comment by remarkablemark** [comment]
I did a quick check in [JSFiddle](https://jsfiddle.net/remarkablemark/rq3zh9dy/) and it looks like `node.childNodes` is returning the proper nodes:

```js
const template = document.createElement('template');
template.innerHTML = '<br>';

console.log('template.childNodes', template.childNodes); // invalid
console.log('template.content.childNodes', template.content.childNodes); // valid
```
