### ISSUE TITLE
Prepare for Chrome User-Agent reduction

### ISSUE THREAD

**Issue by prsdthkr** [remarkablemark/html-dom-parser#225]
#### Description
Chrome is changing how much userAgent data they expose to the browser. Usage of navigator.userAgent in https://github.com/remarkablemark/html-dom-parser/blob/master/lib/client/utilities.js#L138 will throw browser warnings in the future.

#### Possible solution
something like
```js
function isIE() {
  const reducedUAString = navigator?.userAgentData?.brands
              ?.map?.(
                  ({ brand, version }) => (`${brand}/${version}`),
              )?.join?.(' ');
  
  // for other browsers
  if( !reducedUAString ) {
      return  /(MSIE |Trident\/|Edge\/)/.test(navigator.userAgent);
  } else {
    // for chrome
    return  /(MSIE |Trident\/|Edge\/)/.test(reducedUAString);
  }
}
```

#### Additional context
> User-Agent (UA) reduction is the effort to minimize the identifying information shared in the User-Agent string which may be [used for passive fingerprinting](https://www.w3.org/2001/tag/doc/unsanctioned-tracking/#unsanctioned-tracking-tracking-without-user-control). As these [changes are rolled out](https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html), all resource requests will have a reduced User-Agent header. As a result, the return values from certain Navigator interfaces will be reduced, including: navigator.userAgent, navigator.appVersion, and navigator.platform.

https://developer.chrome.com/docs/privacy-sandbox/user-agent/

**Comment by remarkablemark** [comment]
Given Internet Explorer 11 (IE) is going to be deprecated on June 15, 2022, I think it'll be easier to remove IE-related code.
