### ISSUE TITLE
Usage of html-dom-parser-server in browser

### ISSUE THREAD

**Issue by iamcdonald** [remarkablemark/html-dom-parser#30]
Hi,

I'm using your `html-react-parser` npm lib which in turn has a dependency on this repo.
I'd like to make use of the htmlparser2 options but this doesn't work within the browser as the implementation within this repo is swapped out for the `html-dom-parser-client` implementation.

I've quickly changed the package.json in my local version to use the `html-dom-parser-server` implementation and it works fine in the browser (when webpacked) and allows me to provide the options I require.

I'm wondering if the client implementation was/is still needed (given the server implementation wrapping htmlparser2 appears to work fine)?
If so, is there a way I can opt into using the server one regardless?
I couldn't see a way but I could also easily be missing something.

Thanks 

Iain

**Comment by remarkablemark** [comment]
The reason why the client does not have some server options is because the client uses a native DOM implementation whereas the server uses `htmlparser2`. This was done to keep the client bundle small (otherwise the library would be a couple hundred KB).

If you must use the server implementation, you can but be aware of the cost in bundle size and performance.

**Comment by iamcdonald** [comment]
I figured that might be the case.

How would you suggest using the server instance given I'm using `html-react-parser`?
The only option I can see is to try and override the version of `html-dom-parser` via webpack aliasing or something like that.

**Comment by remarkablemark** [comment]
Yes, I think webpack alias might be the only way right now

**Comment by remarkablemark** [comment]
Let me know if you need anything else. Otherwise, are we good to close the issue?

**Comment by iamcdonald** [comment]
👍
