### ISSUE TITLE
Suggest ESM support 

### ISSUE THREAD

**Issue by AlbertAZ1992** [remarkablemark/html-dom-parser#327]
`domhandler` has supported ESM since v5 https://github.com/fb55/domhandler/commit/5582477b37a3fbd0665fadc3be34f08f9db9be9a  

But `html-dom-parser` still imports commonjs format of `domhandler` with the latest version(v5.0.3) https://github.com/remarkablemark/html-dom-parser/blob/master/package.json#L45. 

That will cause some TypeErrors when you try to build a package with `html-dom-parser` to ESM, as `domhandler` import as esm, the uses like `require('domhandler').Text` get undefined:  https://github.com/remarkablemark/html-dom-parser/blob/master/lib/client/utilities.js#L9

So i think `html-dom-parser` should support ESM build

**Comment by remarkablemark** [comment]
Thanks for opening this issue @AlbertAZ1992! Would you be interested in opening a PR?

**Comment by AlbertAZ1992** [comment]
Yes. can’t use ESM packages in CJS.

**Comment by AlbertAZ1992** [comment]
> Thanks for opening this issue @AlbertAZ1992! Would you be interested in opening a PR?

Yes. But since we cannot use ESM in CommonJS, i think that rewrite the `lib/client` with ESM and build to CommonJS is the only way.

**Comment by remarkablemark** [comment]
Can't we follow the same approach as [html-react-parser](https://github.com/remarkablemark/html-react-parser/blob/v3.0.1/index.mjs)? Only a single `index.mjs` was created and the `require` in the other files were untouched
