### ISSUE TITLE
lib/client/html-to-dom.mjs is not a valid ECMAScript Module

### ISSUE THREAD

**Issue by gregatgoogle** [remarkablemark/html-dom-parser#334]
https://github.com/remarkablemark/html-dom-parser/commit/0c4c2b6d86c75cb3dc924afc6fd8501c5d30a876 has added https://github.com/remarkablemark/html-dom-parser/blob/master/lib/client/html-to-dom.mjs with 

```js
module.exports = HTMLDOMParser;
module.exports.default = HTMLDOMParser;
```

which are not valid ECMAScript exports statements ([valid syntax](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax)). `export` and `export default` are, like in [index.mjs](https://github.com/remarkablemark/html-dom-parser/blob/master/index.mjs).

The end result is this is that my project crashes on browser with [ReferenceError: module is not defined](https://stackoverflow.com/questions/63975194/referenceerror-module-is-not-defined).

Could you either revert that change or make it ECMAScript compliant?

**Comment by remarkablemark** [comment]
Would you be open to making a PR? The fix would be the following, right?

```js
export default HTMLDOMParser;
```

**Comment by gregatgoogle** [comment]
I can but I would need to ask my employer for permission to contribute to your code, which could take days (or weeks?). If you are willing to wait, I can do it.

**Comment by remarkablemark** [comment]
Ok no problem, I can take it

**Comment by remarkablemark** [comment]
Release https://github.com/remarkablemark/html-dom-parser/pull/336#issuecomment-1221215010
