### ISSUE TITLE
Can't import the named export 'formatDOM' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by aghArdeshir** [remarkablemark/html-dom-parser#337]
## Expected Behavior

-

## Actual Behavior

I'm receiving this error when I simply try to use the library.
```
error - /app/node_modules/html-dom-parser/lib/client/html-to-dom.mjs
Can't import the named export 'formatDOM' from non EcmaScript module (only default export is available)
```

## Steps to Reproduce

I am actually using `html-react-parser` which is using `html-dom-parser`. But as I checked in node_modules, I have the latest version of both libraries:
```
"html-dom-parser": "^3.1.1",
"html-react-parser": "^3.0.3",
```
which means it includes this fix as well: https://github.com/remarkablemark/html-dom-parser/pull/335
But I am still having this issue.

## Reproducible Demo

This is actually simply how I am using this library:
```ts
import parse from 'html-react-parser';

parse(someString);
```

But this problem is happening inside NextJS.

## Environment

- Version: 3.1.1
- Platform: I am using NextJs, that may be causing the issue as well!
- Browser: Not Applicable, it happens in server

**Comment by remarkablemark** [comment]
Relates to https://github.com/remarkablemark/html-react-parser/issues/662

@aghArdeshir can you provide a reproducible example?

**Comment by aghArdeshir** [comment]
@remarkablemark I'll try to prepare a reproducible repo/sandbox.

But no, in our case, `"html-react-parser": "^3.0.1",` did not help, I hoped 3.0.3 would fix it.

**Comment by QuentinLesauce** [comment]
In my case, "html-react-parser": "^3.0.1" just fixed it.

**Comment by remarkablemark** [comment]
@aghArdeshir you will need to use exact version:

```
"html-react-parser": "3.0.1",
```

**Comment by aghArdeshir** [comment]
Oops :see_no_evil: @remarkablemark yes you are right, it does fix the issue. So the update was causing the problem. Thanks. Reverting back to "3.0.1" fixes it.

The issue is resolved in my case then, but I still continue trying to create a reproducible repo.

Thanks.

**Comment by remarkablemark** [comment]
Thanks @aghArdeshir. I'll try to look for a reproducible example and see if I can fix this bug sometime this week.

**Comment by aghArdeshir** [comment]
I could reproduce it: https://github.com/aghArdeshir/reproduce-html-dom-parser-337

But through creating this reproducible example I found out that the problem is either with another package or outdated package usage.

just clone and do `npm i; npm run dev`

I guess we can close the issue. 

Thanks for your time :heart:

**Comment by remarkablemark** [comment]
Thanks for creating the repo @aghArdeshir! I'll take a look later tonight.

**Comment by remarkablemark** [comment]
Release https://github.com/remarkablemark/html-dom-parser/pull/339#issuecomment-1223371393

**Comment by remarkablemark** [comment]
Release https://github.com/remarkablemark/html-react-parser/pull/668#issuecomment-1223383096
