### ISSUE TITLE
Bug in Nodes implementation of case sensitive tag names

### ISSUE THREAD

**Issue by blizzardengle** [remarkablemark/html-dom-parser#424]
## Expected Behavior

When parsing a complex SVG in browser or in Node the `tagName` (`name`) of many elements should be case sensitive. Here is the [spec list](https://developer.mozilla.org/en-US/docs/Web/SVG/Element#svg_elements_a_to_z) indicating which tags.

## Actual Behavior

When attempting to parse a complex SVG element ([this camera](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg)) in Node several elements are having their names lower-cased instead of being returned in camel-case. Specifically the `radialGradient` and `linearGradient` tags are effected in this example.

## Steps to Reproduce

Attempt to parse just the `svg` code from [this camera](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg) in Node.

## Reproducible Demo

`html-dom-parser` works as expected in the browser: [https://jsfiddle.net/nx7h6wvz/](https://jsfiddle.net/nx7h6wvz/)

`html-dom-parser`  DOES NOT work in Node. Here is how you can test this:

1. Have Node installed and install  `html-dom-parser` 
2. Create a file named `test.js` with the following code:
```js
const Parse = require('html-dom-parser');
const Fs = require('fs');

function printTagNames(parent) {
    let html = '';
    parent.children.forEach((child) => {
        // Skip if not an actual element.
        if (child.type !== 'tag') {
            return;
        }
        // Get and show the tag name.
        const tagName = child.name;
        console.log(tagName);
        // Recurse through the children.
        if (child.children) {
            html += printTagNames(child);
        }
    });
    return html;
}

const code = Parse(Fs.readFileSync('camera.svg').toString());

// Locate SVG:
let svg;
code.forEach((ref) => {
    if (ref.type === 'tag') {
        if (ref.name === 'svg') {
            svg = ref;
        }
    }
});

printTagNames(svg);
```
3. Download the ([this camera](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg)) and place it in the same directory as the `test.js` file. Make sure to rename the `svg` file as `camera.svg`.
4. Run the test in your terminal with: `node test.js`

## Environment

- Version: 3.1.5
- Platform: Linux, Ubuntu Debian, Node v18.13.0
- Browser: Latest Chromium (Not Applicable)
- OS: Pop!_OS

## Keywords

- name
- tagName
- incorrect name case
- case sensitivity
- CASE_SENSITIVE_TAG_NAMES

**Comment by blizzardengle** [comment]
It appears that the [formatTagName(tagName)](https://github.com/remarkablemark/html-dom-parser/blob/master/lib/client/utilities.js#L53) function is missing from the Server (Node) processing.

**Comment by remarkablemark** [comment]
On the server (Node.js), we're using [htmlparser2](https://www.npmjs.com/package/htmlparser2) so I'm surprised if SVG isn't working. I'll try to take a look at your reproducible example later in the day when I have some time.

**Comment by blizzardengle** [comment]
Can confirm this is a "feature" in the upstream [htmlparser2](https://www.npmjs.com/package/htmlparser2). Here is my modified code that uses `htmlparser2` directly.

```js
const Parse = require('htmlparser2');
const Fs = require('fs');

function printTagNames(parent) {
    let html = '';
    parent.children.forEach((child) => {
        // Skip if not an actual element.
        if (child.type !== 'tag') {
            return;
        }
        // Get and show the tag name.
        const tagName = child.name;
        console.log(tagName);
        // Recurse through the children.
        if (child.children) {
            html += printTagNames(child);
        }
    });
    return html;
}

const dom = Parse.parseDocument(Fs.readFileSync('camera.svg').toString());

// Locate SVG:
let svg;
dom.children.forEach((ref) => {
    if (ref.type === 'tag') {
        if (ref.name === 'svg') {
            svg = ref;
        }
    }
});

printTagNames(svg);
```

You can pass in a option to turn on case protection. Here is the modified line of code from above:

```js
const dom = Parse.parseDocument(Fs.readFileSync('camera.svg').toString(), {
    lowerCaseTags: false
});
```

**Comment by blizzardengle** [comment]
Yes, that works! Would you like me to submit a PR later that highlights the need for this Server side? I can also include the other options from `html-dom-parser`.
