### ISSUE TITLE
Bug: Assumes all attributes are lower case

### ISSUE THREAD

**Issue by phawxby** [remarkablemark/html-dom-parser#9]
Some attributes are not supposed to be lowercase, for example [SVG attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg#Specific_attributes).

**Example**
viewBox attribute is made lower case.
```
const htmlToDOM = require('html-dom-parser');

const html = `<svg viewBox="foo"></svg>`;
const output = htmlToDOM(html);

console.log(output);

// Output
// [ { type: 'tag',
//     name: 'svg',
//     attribs: { viewbox: 'foo' },
//     children: [],
//     next: null,
//     prev: null,
//     parent: null } ]
```

**Comment by phawxby** [comment]
Ultimately chased this down to a module not passing though config cars. This can be fixed via options.

**Comment by remarkablemark** [comment]
Great to hear that you figured it out!

Also, feel free to create a PR and update the `README.md` with the link to htmlparser2's [options](https://github.com/fb55/htmlparser2/wiki/Parser-options).
